<a href="https://colab.research.google.com/github/giannishorgos/Numerical-analysis/blob/main/numerical_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Factorizations LU and QR#
  - LU
    - Start with the original square matrix A.

      Initialize two empty matrices: L as a lower triangular matrix and U as an upper triangular matrix.

      Begin with the first row of A and copy it as the first row of U.

      Divide the first row of U by its first element to make the first element of U equal to 1.

      For each row below the first row, perform the following steps:

      a. For each column in the current row, calculate the values of U by subtracting the appropriate multiples of the elements in the row above.

      b. Divide the resulting row of U by its diagonal element to make the diagonal element equal to 1.

      c. Store the multipliers used in step 5a in the corresponding positions of L.

      Once all the rows and columns have been processed, the matrix U will be an upper triangular matrix, and the matrix L will be a lower triangular matrix with ones on its diagonal.

      The matrices L and U obtained from the previous steps represent the LU factorization of the original matrix A.
  - QR
      - Start with the original matrix A.

      Initialize an empty matrix Q as an orthogonal matrix.

      Initialize an empty matrix R as an upper triangular matrix.

      For each column in A (starting from the first column), perform the following steps:

      a. Take the corresponding column vector of A and subtract the projections of that vector onto the previously computed orthogonal basis vectors of Q. This step orthogonalizes the column vector.

      b. Normalize the resulting vector to have unit length. This step ensures that the orthogonal vectors form an orthonormal basis.

      c. Store the resulting vector as a column in Q.

      d. Calculate the coefficients for the linear combination of the orthogonal basis vectors that give the original column vector. These coefficients form the elements of the upper triangular matrix R.

      Once all the columns have been processed, the matrix Q will be an orthogonal matrix, and the matrix R will be an upper triangular matrix.

      The matrices Q and R obtained from the previous steps represent the QR factorization of the original matrix A.  

In [ ]:
# imports
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# LU 
def LUmine(A):
  n = A.shape[0]
  L = np.matrix(np.identity(n))
  U = A
  for j in range(0, n-1):
    for i in range(j+1, n):
      mult = A[i, j] / A[j, j]
      A[i, j + 1 : n] = A[i, j + 1 : n] - mult * A[j, j + 1 : n] 
      U[i, j + 1 : n] = A[i, j + 1 : n]
      L[i, j] = mult
      U[i, j] = 0
  return L, U

In [ ]:
# QR
def QRmine(A):
  n = A.shape[0]
  # print(n)
  Q = np.matrix(np.zeros((n, n)))
  for j in range(n):
    q = A[:,j]

    for i in range(j):
      length_of_leg = A[:, j].T * Q[:, i]
      q = q - length_of_leg[0, 0] * Q[:, i]

    Q[:, j] = q / np.linalg.norm(q)
  R = Q.T * A
  return Q, R




In [ ]:
# Hilber Creation
def createHilbert(n):
  H = np.matrix([[1 / (i + j + 1) for j in range(n)] for i in range(n)])

In [ ]:
A = np.matrix([[1, 2, 54], [4, 5, 23]])
Q, R = QRmine(A)
print("Matrix Q:")
print(Q)
print("Matrix R:")
print(R)
print(f'RES { np.linalg.norm(A - Q*R)}')
createHilbert(4)

(1, 2) (2, 1)
Matrix Q:
[[ 0.24253563  0.9701425 ]
 [ 0.9701425  -0.24253563]]
Matrix R:
[[ 4.12310563e+00  5.33578375e+00  3.54102013e+01]
 [-1.44328993e-15  7.27606875e-01  4.68093756e+01]]
RES 1.6102827228051456e-14
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
